prometheus:
  alertmanager:
    enabled: false
  grafana:
    enabled: false

grafana:
  adminPassword: "admin"

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://my-monitoring-prometheus-server.monitoring.svc.cluster.local
          access: proxy
          isDefault: true
