name: "Terraform CI for Backend"

"on":
    push:
        branches:
            - main
        paths:
            - "modules/00-backend/**"
    pull_request:
        paths:
            - "modules/00-backend/**"

jobs:
    plan:
        name: "Terraform Plan"
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./modules/00-backend

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-south-1

            - name: Terraform Init
              run: terraform init

            - name: Terraform Validate
              run: terraform validate

            - name: Terraform Plan
              run: terraform plan -out=tfplan -input=false -no-color

            - name: Upload Plan and State Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: backend-artifacts
                  path: |
                      ./modules/00-backend/tfplan
                      ./modules/00-backend/terraform.tfstate

    apply:
        name: "Terraform Apply"
        runs-on: ubuntu-latest
        needs: plan

        if: github.ref == 'refs/heads/main' && github.event_name == 'push'

        environment: production

        defaults:
            run:
                working-directory: ./modules/00-backend

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-south-1

            - name: Download Plan and State Artifacts
              uses: actions/download-artifact@v4
              with:
                  name: backend-artifacts
                  path: ./modules/00-backend

            - name: Terraform Init
              run: terraform init

            - name: Terraform Apply
              run: terraform apply -auto-approve tfplan
